version: '3'
services:
  db:
    container_name: database
    image: 'mysql:8.0'
    environment:
      - MYSQL_DATABASE=lms
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=123
      - DATABASE_HOST=db
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  server:
    build: ./
    command: ./app
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=lms
      - DB_USER=root
      - DB_PASS=123
    ports:
      - 8080:8080